name: CI

on: 
  push:
    branches:
      - '*'
  pull_request:
      branches:
        - '*'
  workflow_dispatch:

jobs:

  build-ongaku:
    runs-on: ubuntu-latest
    steps:
      - name: Set up checkout JDK 17
        uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Maven Package
        run: |
          java --version
          mvn --version
          mvn -f /home/runner/work/ongaku-pikature/ongaku-pikature/ongaku-pikature/pom.xml -B clean compile package -DskipTests
          echo build project!
          
  test-ongaku:
    needs: build-ongaku
    runs-on: ubuntu-latest
    steps:
      - name: set up JDK 17
        uses: actions/checkout@v3
        with:
          java-version: 1.17
      - name: Maven Verify
        run: mvn -B clean verify
      - name: Test Coverage
        uses: codecov/codecov-action@v1
      

    
    
