name: CI

on: 
  push:
    branches:
      - '*'
  pull_request:
      branches:
        - '*'
  workflow_dispatch:

jobs:

  build-ongaku:
    runs-on: ubuntu-latest
    steps:
      - name: set up JDK 17
        uses: actions/checkout@v3
        with:
          java-version: 1.17
      - name: Maven Package
        run: |
          mvn -B -X clean compile package -DskipTests
          echo build project!
          
  test-ongaku:
    needs: build-ongaku
    runs-on: ubuntu-latest
    steps:
      - name: set up JDK 17
        uses: actions/checkout@v3
        with:
          java-version: 1.17
      - name: Maven Verify
        run: mvn -B clean verify
      - name: Test Coverage
        uses: codecov/codecov-action@v1
      

    
    
